version: '3'
services:
        web:
                image: devops_v1
                build: .
                ports:
                        - "8180:8180"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
